### ISSUE TITLE
Variable "$_is_personal_area" in breadcrumbs.html doesn't work as expected.

### ISSUE THREAD

**Issue by Trost123** [webasyst/dummy-theme#1]
The line:
`{$_is_personal_area = ( $wa->currentUrl() == $wa->getUrl('/frontend/my') )}`
Doesn't ever return true for me, I'm using this as a workaround:
Because $wa->getUrl('/frontend/my') returns "/my/".
And $wa->currentUrl() returns /my/profile/, my/orders/ etc.

My workaround is to use:
`{$_is_personal_area = ( strpos($wa->currentUrl(), $wa->getUrl('/frontend/my')) !== false )}`
But it's not the best solution.

This doesn't seem to work as expected too, if you use ref-link like www.yoursite.com/?refdata="foo":
`{$_is_main_page = ( $wa->currentUrl() == $wa_app_url )}`
I use:
`{$_is_main_page = {$action=="default"}}`
But again, it's not perfect, use a better solution if you come up with one.

**Comment by Leonix** [comment]
This changed in https://github.com/webasyst/dummy-theme/commit/de466a01e94c699e2af559d38de67c1b81ce2cbf and should properly work now.
