### ISSUE TITLE
Footer jumps on resize down.

### ISSUE THREAD

**Issue by Trost123** [webasyst/dummy-theme#2]
Footer begins to jump up and down if you drag the bottom border of a browser up. (when the page is short enough for this script to work)

I fixed this by commenting out delta check in dummy.js. If you shrink window vertically - delta is <1, and footers starts to jump.
```
      // if (delta > 0) {
      $main.css({
        "min-height": main_height + delta + "px"
      });
      // } else {
      //   $main.removeAttr("style");
      // }
```

**Comment by Leonix** [comment]
Should have been fixed since https://github.com/webasyst/dummy-theme/commit/ab3cba81a5967507df93b1d9db2cfb769ce1a29c
